### PR TITLE
Compatibility with ATK/data:2.1

### PR DESCRIPTION
**Pull request by karakal**

### CODE REVIEW

**Review by DarkSide666 — CHANGES_REQUESTED** [review]
What's the point of this?
Array Persistence data is set to empty array by default too.

**Comment by karakal** [comment]
> What's the point of this?
> Array Persistence data is set to empty array by default too.

The point of this is, that it will not run if you don't set this parameter.

**Review by DarkSide666 — CHANGES_REQUESTED** [review]
I still don't see how this currently fails.
Can you please add testcase to cover this issue?

**Comment by karakal** [comment]
Why was this closed when it was not corrected in the development branch??????

**Pull request closed without merging**
